### PR TITLE
Fixed ciMode not writing draw.io diagrams to filesystem

### PR DESCRIPTION
**Pull request by adriannieto**
ciMode for drawio does not save the file anywere, this will fix log output and filename generation

### CODE REVIEW

**Review by ljacobsson — APPROVED** [review]

**Comment by ljacobsson** [comment]
Thanks for this @adriannieto!

I'll get this released straight away

**Comment by adriannieto** [comment]
@ljacobsson  did you actually merge the code?

**Comment by ljacobsson** [comment]
Ouch - I was a bit fast there. Thanks for heads up

**Comment by adriannieto** [comment]
No prob, I'm just looking forward to use your awesome job!

**Comment by ljacobsson** [comment]
Thanks :-)

Please let me know or submit another PR if you come across any other issues

**Pull request merged**
